Read shell's startup files at graphical logins (lightdm)
Lightdm does not read shell startup files (/etc/profile,
~/.profile) by default, and this isn't considered as a bug
by lightdm developers. To address this issue we soure
these files in lightdm's session-wrapper Xsession.

Related issues:
https://bugs.launchpad.net/ubuntu/+source/lightdm/+bug/794315
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=752129

Signed-off-by: Cihangir Akturk <cihangir@pardus.org.tr>

diff --git a/debian/local/Xsession b/debian/local/Xsession
--- a/debian/local/Xsession
+++ b/debian/local/Xsession
@@ -78,6 +78,15 @@ exec >>"$ERRFILE" 2>&1
 
 echo "$PROGNAME: X session started for $LOGNAME at $(date)"
 
+# Load profile
+set +e
+for file in "/etc/profile" "$HOME/.profile"; do
+  if [ -f "$file" ] && ! . "$file"; then
+    echo "Error loading $file"
+  fi
+done
+set -e
+
 # sanity check; is our session script directory present?
 if [ ! -d "$SYSSESSIONDIR" ]; then
   errormsg "no \"$SYSSESSIONDIR\" directory found; aborting."
